/**
 * MarkdownEngine — Assembles the final README.md from all collected data.
 *
 * This is the **final output pipeline**. It receives structured data from
 * every stage of the analysis pipeline (metadata, tech stack, commands,
 * features, APIs, AI-generated content, directory tree) and produces a
 * polished, deterministic README.md.
 *
 * Features:
 *   • Deterministic section ordering with graceful degradation
 *   • Badge generation from TechMapper data
 *   • Command tables from CommandInference results
 *   • Feature lists from FeatureExtractor results
 *   • API endpoint tables from APIExtractor results
 *   • AI content integration with fallback sections
 *   • Configurable output style
 *   • Enhanced Markdown formatting with tables, lists, code blocks, links, emojis
 *   • Professional visual structure with proper spacing and hierarchy
 *
 * Data flow:
 *   `MetadataExtractor`    → project name, description, license, repo
 *   `TechMapper`           → project types, languages → badges
 *   `CommandInference`     → validated commands → command table
 *   `FeatureExtractor`     → validated features → feature list
 *   `APIExtractor`         → validated endpoints → API table
 *   `AIEngine`             → AI-generated overview, usage, etc.
 *   `TreeGenerator`        → ASCII directory tree
 *
 * @module utils/markdown-engine
 */

import { ProjectMetadata } from '../core/metadata-extractor.js';
import { TechReport, TechMapper } from '../core/tech-mapper.js';
import { InferenceResult, ValidatedCommand } from '../core/command-inference.js';
import { FeatureExtractionResult, ValidatedFeature } from '../core/feature-extractor.js';
import { APIExtractionResult, ValidatedAPIEndpoint } from '../core/api-extractor.js';
import { SanitizedData } from '../core/data-sanitizer.js';
import { BadgeGenerator, BadgeStyle } from './badge.js';
import type { SectionId } from './templates.js';

// ─────────────────────────── Types ───────────────────────────

/**
 * Complete input data required by the MarkdownEngine.
 */
export interface EngineInput {
  /** Project metadata (name, version, description, etc.) */
  metadata: ProjectMetadata;
  /** Detected project types and language breakdown */
  techReport: TechReport;
  /** Validated commands from inference pipeline */
  inferenceResult?: InferenceResult | null;
  /** Validated features from extraction pipeline */
  featureResult?: FeatureExtractionResult | null;
  /** Validated API endpoints from extraction pipeline */
  apiResult?: APIExtractionResult | null;
  /** AI-generated content sections (may be partial) */
  aiContent?: AIContent | null;
  /** ASCII directory tree string */
  tree?: string;
  /** Pre-sanitized data from DataSanitizer (used when available) */
  sanitizedData?: SanitizedData | null;
  /** Badge style to use throughout */
  badgeStyle?: BadgeStyle;
}

/**
 * AI-generated content sections (optional, may be partial).
 */
export interface AIContent {
  /** AI-generated project overview */
  overview?: string;
  /** AI-generated features section */
  features?: string;
  /** AI-generated installation instructions */
  installation?: string;
  /** AI-generated usage examples */
  usage?: string;
  /** AI-generated API documentation */
  apiDocs?: string;
  /** Full AI-generated README (used as-is if complete, parsed for sections otherwise) */
  fullReadme?: string;
}

/**
 * Configuration for the MarkdownEngine.
 */
export interface EngineConfig {
  /** Whether to include the directory tree section */
  includeTree: boolean;
  /** Whether to include the command table section */
  includeCommands: boolean;
  /** Whether to include the features section */
  includeFeatures: boolean;
  /** Whether to include the API endpoints section */
  includeAPIs: boolean;
  /** Whether to include badges (shields.io) */
  includeBadges: boolean;
  /** Whether to include a "Generated by" footer */
  includeFooter: boolean;
  /** Maximum number of commands to display */
  maxCommands: number;
  /** Maximum number of features to display */
  maxFeatures: number;
  /** Maximum number of API endpoints to display */
  maxAPIs: number;
  /** Template name being used */
  template?: string;
  /** List of section IDs to include in output */
  sections?: SectionId[];
  /** Badge style to use throughout */
  badgeStyle?: BadgeStyle;
}

/** Default configuration. */
const DEFAULT_CONFIG: Readonly<EngineConfig> = Object.freeze({
  includeTree: true,
  includeCommands: true,
  includeFeatures: true,
  includeAPIs: true,
  includeBadges: true,
  includeFooter: true,
  maxCommands: 10,
  maxFeatures: 15,
  maxAPIs: 20,
});

// ─────────────────────────── Category display names ───────────────────────────

/** Human-readable labels for command categories. */
const CATEGORY_LABELS: ReadonlyMap<string, string> = new Map([
  ['install', '📦  Install'],
  ['build', '🔨  Build'],
  ['test', '🧪  Test'],
  ['run', '🚀  Run'],
  ['dev', '🛠  Development'],
  ['lint', '✨  Lint'],
  ['format', '🎨  Format'],
  ['clean', '🧹  Clean'],
  ['deploy', '📤  Deploy'],
  ['other', '📋  Other'],
]);

/** Human-readable labels for feature categories. */
const FEATURE_CATEGORY_LABELS: ReadonlyMap<string, string> = new Map([
  ['core', 'Core'],
  ['ui', 'User Interface'],
  ['api', 'API & Integrations'],
  ['utility', 'Utilities'],
  ['other', 'Other'],
]);

// ─────────────────────────── Helpers ───────────────────────────

/**
 * Strip Markdown code fences and heading markers from AI content.
 */
function cleanAIContent(text?: string): string {
  if (!text) return '';
  return text
    .replace(/^```markdown\s*/i, '')
    .replace(/^```\s*/i, '')
    .replace(/```\s*$/i, '')
    .trim();
}

/**
 * Escape a string for safe inclusion in a Markdown table cell.
 */
function escapeTableCell(value: string): string {
  return value.replace(/\|/g, '\\|').replace(/\n/g, '<br>');
}

// ─────────────────────────── Engine ───────────────────────────

/**
 * `MarkdownEngine` assembles all collected data into a final README.md string.
 *
 * @example
 * ```ts
 * const engine = new MarkdownEngine({ includeBadges: true, includeTree: true });
 *
 * const readme = engine.build({
 *   metadata,
 *   techReport,
 *   inferenceResult,
 *   featureResult,
 *   apiResult,
 *   aiContent: { overview: '...', usage: '...' },
 *   tree: directoryTreeString,
 * });
 *
 * await fs.writeFile('README.md', readme);
 * ```
 */
export class MarkdownEngine {
  private config: EngineConfig;

  constructor(config: Partial<EngineConfig> = {}) {
    this.config = { ...DEFAULT_CONFIG, ...config };
  }

  // ── Public API ──────────────────────────────────────────────

  /**
   * Build the complete README.md string from all input data.
   *
   * Sections are assembled in a fixed, professional order:
   *   1. Title & badges (with emojis and enhanced formatting)
   *   2. Overview (AI or heuristic, with emojis)
   *   3. Key Features (AI-extracted or static, with emojis and categorization)
   *   4. Technology Stack (badges from TechMapper, with enhanced formatting)
   *   5. Commands (from CommandInference, with source indicators)
   *   6. Project Structure (ASCII tree, with emojis)
   *   7. Getting Started / Installation (AI or static, with prerequisites)
   *   8. Usage Examples (AI or heuristic, with development/production modes)
   *   9. API Endpoints (from APIExtractor, with method badges)
   *   10. Contributing & License (with badges and emojis)
   *   11. Footer (with centered formatting)
   *
   * @param input - All data required for README generation.
   * @returns The complete README.md as a string.
   */
  public build(input: EngineInput): string {
    const sections: string[] = [];
    const config = this.config;

    // Only build sections that are in the config.sections array
    if (config.sections?.includes('header')) {
      sections.push(this.buildTitleAndBadges(input));
    }
    if (config.sections?.includes('overview')) {
      sections.push(this.buildOverview(input));
    }
    if (config.sections?.includes('features') && this.config.includeFeatures) {
      sections.push(this.buildFeatures(input));
    }
    if (config.sections?.includes('tech-stack')) {
      sections.push(this.buildTechStack(input));
    }
    if (config.sections?.includes('commands') && this.config.includeCommands && input.inferenceResult) {
      sections.push(this.buildCommands(input.inferenceResult));
    }
    if (config.sections?.includes('structure') && this.config.includeTree && input.tree) {
      sections.push(this.buildTreeSection(input.tree));
    }
    if (config.sections?.includes('installation')) {
      sections.push(this.buildInstallation(input));
    }
    if (config.sections?.includes('usage')) {
      sections.push(this.buildUsage(input));
    }
    if (config.sections?.includes('api-reference') && this.config.includeAPIs && input.apiResult) {
      sections.push(this.buildAPISection(input.apiResult));
    }
    if (config.sections?.includes('contributing') || config.sections?.includes('license')) {
      sections.push(this.buildMetaSections(input.metadata));
    }
    if (config.sections?.includes('footer') && this.config.includeFooter) {
      sections.push(this.buildFooter());
    }

    // Join sections with proper spacing and ensure final newline
    return sections
      .filter(section => section.length > 0)
      .join('\n\n') + '\n';
  }

  // ── Section builders ──────────────────────────────────────

  /**
   * Build the title and badges section with enhanced formatting.
   */
  private buildTitleAndBadges(input: EngineInput): string {
    const lines: string[] = [];
    const badgeStyle = this.config.badgeStyle || input.badgeStyle || 'for-the-badge';

    // Title with emoji for visual appeal
    const title = input.metadata.name || 'Project';
    const titleEmoji = this.getProjectEmoji(input.techReport);
    lines.push(`# ${titleEmoji} ${title}`);

    // Version badge
    if (input.metadata.version && input.metadata.version !== '0.0.0') {
      const versionBadge = BadgeGenerator.generateMarkdown({
        label: `v${input.metadata.version}`,
        color: 'informational',
        style: badgeStyle,
      });
      lines.push(versionBadge);
    }

    // License badge
    if (input.metadata.license?.spdx) {
      const licenseBadge = BadgeGenerator.generateMarkdown({
        label: input.metadata.license.spdx,
        color: 'blue',
        style: badgeStyle,
      });
      lines.push(licenseBadge);
    }

    if (lines.length > 1) {
      lines.push(''); // blank line after badges
    }

    // Tech stack badges from TechMapper with better spacing
    if (this.config.includeBadges && input.techReport.projectTypes.length > 0) {
      const techBadges = BadgeGenerator.fromProjectTypes(
        input.techReport.projectTypes,
        badgeStyle,
      );
      lines.push(techBadges);
      lines.push(''); // spacing after badges
    }

    // Add description as a subtitle if available
    if (input.metadata.description) {
      lines.push('');
      lines.push(`> ${input.metadata.description}`);
      lines.push('');
    }

    return lines.join('\n');
  }

  /**
   * Build the project overview section with enhanced formatting.
   */
  private buildOverview(input: EngineInput): string {
    const aiOverview = cleanAIContent(input.aiContent?.overview);

    if (aiOverview) {
      // If AI provided content, use it directly
      return `## 📖 Overview\n\n${aiOverview}`;
    }

    // Fallback: generate from metadata with better formatting
    const desc = input.metadata.description;
    if (desc) {
      return `## 📖 Overview\n\n${desc}`;
    }

    // Static fallback with enhanced formatting
    const projectType = input.techReport.projectTypes.map((p) => p.label).join(' and ') || 'a';
    const languages = Array.from(input.techReport.languages.values())
      .map(l => l.name)
      .slice(0, 3)
      .join(', ');

    const lines: string[] = [
      '## 📖 Overview',
      '',
      `${input.metadata.name || 'This project'} is ${projectType} project.`,
    ];

    if (languages) {
      lines.push('');
      lines.push(`Built with ${languages}.`);
    }

    return lines.join('\n');
  }

  /**
   * Build the Key Features section with enhanced formatting.
   */
  private buildFeatures(input: EngineInput): string {
    const aiFeatures = cleanAIContent(input.aiContent?.features);

    // If AI provided a features section, use it
    if (aiFeatures && !aiFeatures.startsWith('#')) {
      return `## ✨ Key Features\n\n${aiFeatures}`;
    }

    // Use validated features from FeatureExtractor
    if (input.featureResult && input.featureResult.validated.length > 0) {
      return this.buildFeaturesFromExtracted(input.featureResult.validated);
    }

    // No features to display
    return '';
  }

  /**
   * Build features from validated extraction results with enhanced formatting.
   */
  private buildFeaturesFromExtracted(features: ValidatedFeature[]): string {
    const lines: string[] = ['## ✨ Key Features', ''];

    // Group by category
    const byCategory = new Map<string, ValidatedFeature[]>();
    for (const feature of features.slice(0, this.config.maxFeatures)) {
      const cat = feature.category || 'other';
      if (!byCategory.has(cat)) byCategory.set(cat, []);
      byCategory.get(cat)!.push(feature);
    }

    if (byCategory.size === 1 && byCategory.has('other')) {
      // Single category, just list them with emojis
      lines.push(...features.slice(0, this.config.maxFeatures).map((f, i) => {
        const emoji = this.getFeatureEmoji(i);
        return `${emoji} **${f.name}** — ${f.description}`;
      }));
    } else {
      for (const [cat, feats] of byCategory) {
        const label = FEATURE_CATEGORY_LABELS.get(cat) || cat;
        const catEmoji = this.getCategoryEmoji(cat);
        lines.push(`### ${catEmoji} ${label}`, '');
        lines.push(...feats.map((f, i) => {
          const emoji = this.getFeatureEmoji(i);
          return `${emoji} **${f.name}** — ${f.description}`;
        }));
        lines.push('');
      }
    }

    return lines.join('\n').trim();
  }

  /**
   * Build the Technology Stack section with enhanced formatting.
   */
  private buildTechStack(input: EngineInput): string {
    const lines: string[] = ['## 🛠️ Technology Stack', ''];
    const badgeStyle = this.config.badgeStyle || input.badgeStyle || 'for-the-badge';

    // Project types with badges
    if (input.techReport.projectTypes.length > 0) {
      const typeBadges = input.techReport.projectTypes.map(p => 
        BadgeGenerator.fromProjectType(p, badgeStyle)
      ).join(' ');
      lines.push(`**Project Type:** ${typeBadges}`);
      lines.push('');
    }

    // Languages with counts and badges
    if (input.techReport.languages.size > 0) {
      const langEntries = Array.from(input.techReport.languages.entries())
        .sort((a, b) => b[1].fileCount - a[1].fileCount);
      
      lines.push('**Languages:**');
      for (const [name, info] of langEntries.slice(0, 5)) {
        const langBadge = BadgeGenerator.fromLanguage(info, badgeStyle);
        lines.push(`- ${langBadge} (${info.fileCount} files)`);
      }
      lines.push('');
    }

    // Total files
    lines.push(`**Files Analysed:** ${input.techReport.totalFiles}`);

    return lines.join('\n');
  }

  /**
   * Build the Commands section as a Markdown table with enhanced formatting.
   */
  private buildCommands(inference: InferenceResult): string {
    const commands = inference.commands.slice(0, this.config.maxCommands);

    if (commands.length === 0) return '';

    const lines: string[] = [
      '## 🚀 Commands',
      '',
      '| Category | Command | Description |',
      '|----------|---------|-------------|',
    ];

    for (const cmd of commands) {
      const label = CATEGORY_LABELS.get(cmd.category) || cmd.category;
      const sourceIcon = cmd.source === 'heuristic' ? '⚙️' : cmd.source === 'static-analysis' ? '◆' : '✦';
      lines.push(
        `| ${label} | \`${cmd.command}\` | ${escapeTableCell(cmd.description)} ${sourceIcon} |`,
      );
    }

    if (inference.usedFallback) {
      lines.push('');
      lines.push('> [!NOTE]');
      lines.push(
        '> These commands were generated from heuristics based on the detected project type. Verify before use.',
      );
    }

    return lines.join('\n');
  }

  /**
   * Build the directory tree section with enhanced formatting.
   */
  private buildTreeSection(tree: string): string {
    if (!tree.trim()) return '';

    const lines: string[] = [
      '## 📁 Project Structure',
      '',
      '```text',
      tree.trim(),
      '```',
    ];

    return lines.join('\n');
  }

  /**
   * Build the Installation section with enhanced formatting.
   */
  private buildInstallation(input: EngineInput): string {
    const aiInstall = cleanAIContent(input.aiContent?.installation);

    if (aiInstall) {
      return `## 📦 Getting Started\n\n${aiInstall}`;
    }

    // Build from inferred commands with better formatting
    const installCmd = input.inferenceResult?.commands.find((c) => c.category === 'install');
    const buildCmd = input.inferenceResult?.commands.find((c) => c.category === 'build');

    const lines: string[] = ['## 📦 Getting Started', ''];

    if (installCmd || buildCmd) {
      lines.push('### Prerequisites', '');
      lines.push('Ensure you have the appropriate runtime installed for this project.');
      lines.push('');

      // Detect runtime from tech stack
      const hasNode = input.techReport.projectTypes.some(p => p.label.toLowerCase().includes('node') || p.label.toLowerCase().includes('javascript') || p.label.toLowerCase().includes('typescript'));
      const hasPython = input.techReport.projectTypes.some(p => p.label.toLowerCase().includes('python'));
      const hasRust = input.techReport.projectTypes.some(p => p.label.toLowerCase().includes('rust'));
      const hasGo = input.techReport.projectTypes.some(p => p.label.toLowerCase().includes('go'));

      if (hasNode) {
        lines.push('- **Node.js** (Latest LTS version recommended)');
      }
      if (hasPython) {
        lines.push('- **Python** 3.8 or higher');
      }
      if (hasRust) {
        lines.push('- **Rust** (latest stable)');
      }
      if (hasGo) {
        lines.push('- **Go** 1.16 or higher');
      }
      lines.push('');

      lines.push('### Installation', '');

      if (installCmd) {
        lines.push('Install dependencies:');
        lines.push('');
        lines.push('```bash');
        lines.push(installCmd.command);
        lines.push('```');
        lines.push('');
      }

      if (buildCmd) {
        lines.push('Build the project:');
        lines.push('');
        lines.push('```bash');
        lines.push(buildCmd.command);
        lines.push('```');
      }
    } else {
      lines.push(
        'Clone the repository and follow the setup instructions specific to this project type.',
      );
    }

    return lines.join('\n');
  }

  /**
   * Build the Usage section with enhanced formatting.
   */
  private buildUsage(input: EngineInput): string {
    const aiUsage = cleanAIContent(input.aiContent?.usage);

    if (aiUsage) {
      return `## 💻 Usage\n\n${aiUsage}`;
    }

    // Build from inferred run command with better formatting
    const runCmd = input.inferenceResult?.commands.find((c) => c.category === 'run');
    const testCmd = input.inferenceResult?.commands.find((c) => c.category === 'test');

    if (runCmd || testCmd) {
      const lines: string[] = [
        '## 💻 Usage',
        '',
      ];

      if (testCmd) {
        lines.push('### Testing');
        lines.push('');
        lines.push('Run the test suite:');
        lines.push('');
        lines.push('```bash');
        lines.push(testCmd.command);
        lines.push('```');
        lines.push('');
      }

      if (runCmd) {
        lines.push('### Running the Application');
        lines.push('');
        lines.push('Run the application:');
        lines.push('');
        lines.push('```bash');
        lines.push(runCmd.command);
        lines.push('```');
      }

      return lines.join('\n');
    }

    return '';
  }

  /**
   * Build the API Endpoints section with enhanced formatting.
   */
  private buildAPISection(apiResult: APIExtractionResult): string {
    const endpoints = apiResult.validated.slice(0, this.config.maxAPIs);

    if (endpoints.length === 0) return '';

    const lines: string[] = [
      '## 🔌 API Endpoints',
      '',
    ];
    const badgeStyle = this.config.badgeStyle || 'flat';

    // API style summary with badges
    if (apiResult.apiStyle.type !== 'unknown') {
      const styleBadge = BadgeGenerator.generateMarkdown({
        label: apiResult.apiStyle.type,
        color: 'green',
        style: badgeStyle,
      });
      lines.push(`**API Style:** ${styleBadge}`);
      
      if (apiResult.apiStyle.hasVersioning && apiResult.apiStyle.versionPrefix) {
        lines.push(`**Versioning:** \`${apiResult.apiStyle.versionPrefix}\``);
      }
      
      if (apiResult.apiStyle.consistentNaming) {
        lines.push(`**Naming Convention:** ${apiResult.apiStyle.namingStyle || 'consistent'}`);
      }
      
      lines.push('');
    }

    // Enhanced table with method badges
    lines.push('| Method | Endpoint | Description |');
    lines.push('|--------|----------|-------------|');

    for (const ep of endpoints) {
      const methodBadge = this.httpMethodBadge(ep.method, badgeStyle);
      lines.push(
        `| ${methodBadge} | \`${ep.path}\` | ${escapeTableCell(ep.description || '—')} |`,
      );
    }

    // Add statistics if available
    if (apiResult.stats.validatedCount > 0) {
      lines.push('');
      lines.push(`**Total Endpoints:** ${apiResult.stats.validatedCount} validated`);
    }

    return lines.join('\n');
  }

  /**
   * Build Contributing and License sections from metadata with enhanced formatting.
   */
  private buildMetaSections(metadata: ProjectMetadata): string {
    const lines: string[] = [];
    const badgeStyle = this.config.badgeStyle || 'flat';

    // Contributing
    if (metadata.repository?.url) {
      lines.push(
        '## 🤝 Contributing',
        '',
        `Contributions are welcome! Please open an issue or submit a pull request at [${metadata.name || 'the repository'}](${metadata.repository.url}).`,
        '',
      );
    }

    // License
    if (metadata.license?.spdx || metadata.license?.name) {
      const licenseText = metadata.license.spdx || metadata.license.name!;
      const licenseBadge = BadgeGenerator.generateMarkdown({
        label: licenseText,
        color: 'blue',
        style: badgeStyle,
      });
      lines.push(
        '## 📄 License',
        '',
        `This project is licensed under the ${licenseBadge} License.`,
        '',
      );
    }

    return lines.join('\n').trim();
  }

  /**
   * Build the footer with enhanced formatting.
   */
  private buildFooter(): string {
    return `---\n\n<div align="center">\n\n**Generated with ❤️ by [README-AI-Gen](https://github.com/readme-ai-gen)**\n\n</div>`;
  }

  // ── Enhanced Helpers ──────────────────────────────────────────────

  /**
   * Return an emoji for an HTTP method.
   */
  private httpMethodEmoji(method: string): string {
    switch (method.toUpperCase()) {
      case 'GET': return '🟢';
      case 'POST': return '🔵';
      case 'PUT': return '🟡';
      case 'PATCH': return '🟠';
      case 'DELETE': return '🔴';
      default: return '⚪';
    }
  }

  /**
   * Return a badge for an HTTP method.
   */
  private httpMethodBadge(method: string, badgeStyle: BadgeStyle = 'flat'): string {
    const colors: Record<string, string> = {
      'GET': 'green',
      'POST': 'blue',
      'PUT': 'yellow',
      'PATCH': 'orange',
      'DELETE': 'red',
    };
    
    const color = colors[method.toUpperCase()] || 'gray';
    return BadgeGenerator.generateMarkdown({
      label: method.toUpperCase(),
      color: color,
      style: badgeStyle,
    });
  }

  /**
   * Return an emoji for a project type.
   */
  private getProjectEmoji(techReport: TechReport): string {
    const types = techReport.projectTypes.map(p => p.label.toLowerCase()).join(' ');
    
    if (types.includes('react') || types.includes('vue') || types.includes('angular')) return '⚛️';
    if (types.includes('node') || types.includes('javascript') || types.includes('typescript')) return '🟨';
    if (types.includes('python')) return '🐍';
    if (types.includes('rust')) return '🦀';
    if (types.includes('go')) return '🐹';
    if (types.includes('java')) return '☕';
    if (types.includes('ruby')) return '💎';
    if (types.includes('php')) return '🐘';
    if (types.includes('swift')) return '🍎';
    if (types.includes('kotlin')) return '🤖';
    if (types.includes('dart')) return '🎯';
    if (types.includes('web') || types.includes('html') || types.includes('css')) return '🌐';
    if (types.includes('mobile') || types.includes('android') || types.includes('ios')) return '📱';
    if (types.includes('desktop') || types.includes('electron')) return '🖥️';
    if (types.includes('api') || types.includes('rest') || types.includes('graphql')) return '🔌';
    if (types.includes('cli') || types.includes('command')) return '💻';
    if (types.includes('library') || types.includes('package')) return '📦';
    if (types.includes('framework')) return '🏗️';
    
    return '🚀';
  }

  /**
   * Return an emoji for a feature category.
   */
  private getCategoryEmoji(category: string): string {
    const emojis: Record<string, string> = {
      'core': '⚙️',
      'ui': '🎨',
      'api': '🔌',
      'utility': '🛠️',
      'other': '📋',
    };
    return emojis[category] || '📋';
  }

  /**
   * Return an emoji for a feature item (cycling through a set).
   */
  private getFeatureEmoji(index: number): string {
    const emojis = ['✨', '🎯', '🚀', '💡', '🔥', '⭐', '🎪', '🎨', '🛡️', '🔧'];
    return emojis[index % emojis.length];
  }
}
